server:
  port: 1231

eureka:
  instance:
    hostname: register-center
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://127.0.0.1:1231/eureka