server:
  port: 1237

spring:
  application:
    name: ticket-server
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 123456
    jedis:
      pool:
        max-active: 20
        max-wait: 30000
        max-idle: 8
        min-idle: 0
    timeout: 10000

eureka:
  instance:
    instance-id: ticket-server-1237
    appname: ${spring.application.name}
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://127.0.0.1:1231/eureka
