server:
  port: 1236

spring:
  application:
    name: login-sercer
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tt_login?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 12345687
    druid:
      filters: stat,wall
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: /druid/*,*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico
        session-stat-enable: true
        session-stat-max-count: 10
        principal-session-name: tt_session
        principal-cookie-name: tt_cookie
        profile-enable: true
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: false
        login-username: admin
        login-password: 123456
        allow: 127.0.0.1
      aop-patterns: com.lcf.service.*
      initial-size: 5
      max-active: 20
      min-idle: 0
      max-wait: 60000
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 123456
    jedis:
      pool:
        max-active: 20
        max-wait: 30000
        max-idle: 8
        min-idle: 0
    timeout: 10000

eureka:
  instance:
    instance-id: login-sercer-1236
    appname: ${spring.application.name}
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://127.0.0.1:1231/eureka

mybatis:
  mapper-locations: classpath:/mappers/**.xml
